# LocaAI/config/settings.py
"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv
from chatbot.rag_settings import RAG_SETTINGS

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(dotenv_path=os.path.join(os.path.dirname(__file__), "..", ".env"))

# GeoDjango 설정 - 프로젝트 내장 GDAL 라이브러리 사용
GDAL_LIBS_ROOT = os.path.join(BASE_DIR, 'gdal_libs')

# 🔧 개선된 GDAL 라이브러리 설정 (팀원 환경 호환성 강화)
def setup_gdal_environment():
    """GDAL 환경을 안전하게 설정하는 함수"""
    try:
        if os.path.exists(GDAL_LIBS_ROOT):
            # PATH 환경변수에 추가 (Windows 경로 구분자 사용)
            current_path = os.environ.get('PATH', '')
            if GDAL_LIBS_ROOT not in current_path:
                os.environ['PATH'] = GDAL_LIBS_ROOT + ';' + current_path
            
            # PROJ 설정 (필수)
            os.environ['PROJ_LIB'] = GDAL_LIBS_ROOT
            os.environ['PROJ_NETWORK'] = 'OFF'
            os.environ['PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY'] = 'YES'
            os.environ['PROJ_CURL_ENABLED'] = 'NO'
            os.environ['PROJ_DEBUG'] = '0'
            
            # GDAL 추가 설정 (안정성 향상)
            os.environ['GDAL_DATA'] = GDAL_LIBS_ROOT
            os.environ['GDAL_DRIVER_PATH'] = GDAL_LIBS_ROOT
            
            # 라이브러리 경로 탐지 (여러 버전 지원)
            gdal_patterns = ['gdal*.dll', 'libgdal*.dll']
            geos_patterns = ['geos_c.dll', 'libgeos_c*.dll']
            spatialite_patterns = ['mod_spatialite.dll', 'libspatialite*.dll']
            
            def find_dll(patterns):
                for pattern in patterns:
                    import glob
                    matches = glob.glob(os.path.join(GDAL_LIBS_ROOT, pattern))
                    if matches:
                        return matches[0]
                return None
            
            # DLL 경로 설정
            gdal_dll = find_dll(gdal_patterns)
            geos_dll = find_dll(geos_patterns)
            spatialite_dll = find_dll(spatialite_patterns)
            
            if gdal_dll and os.path.exists(gdal_dll):
                globals()['GDAL_LIBRARY_PATH'] = gdal_dll
            if geos_dll and os.path.exists(geos_dll):
                globals()['GEOS_LIBRARY_PATH'] = geos_dll
            if spatialite_dll and os.path.exists(spatialite_dll):
                globals()['SPATIALITE_LIBRARY_PATH'] = spatialite_dll
            
            print(f"[OK] 프로젝트 내장 GDAL 라이브러리 사용: {GDAL_LIBS_ROOT}")
            return True
        else:
            print(f"[WARNING] GDAL 라이브러리 폴더가 존재하지 않습니다: {GDAL_LIBS_ROOT}")
            return False
    except Exception as e:
        print(f"[ERROR] GDAL 설정 중 오류 발생: {e}")
        return False

# GDAL 환경 설정 실행
gdal_setup_success = setup_gdal_environment()

if not gdal_setup_success:
    print("[INFO] 시스템에 설치된 GDAL을 사용합니다.")
    print("[HINT] 팀원분의 경우 다음을 시도해보세요:")
    print("       1. pip install GDAL")
    print("       2. conda install gdal (Anaconda 사용 시)")
    print("       3. 또는 프로젝트의 gdal_libs 폴더 확인")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# 환경변수 기반 보안 설정 (개선됨)
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-your-secret-key')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True').lower() in ('true', '1', 'yes', 'on')

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')
ASGI_APPLICATION = "config.asgi.application"

# Application definition

INSTALLED_APPS = [
    "rest_framework",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.gis",  # GeoDjango 지원 추가
    "main",  # 메인 웹 디자인 앱
    "border",
    "channels",
    "custom_auth",
    "chatbot",
    "GeoDB",  # 지오메트리 데이터베이스 관리 앱
    "AI_Analyzer",  # AI 상권분석 앱
    "leaflet",  # 지도 기능 (공간정보용)
    "taggit",   # 태그 기능 (복사된 데이터용)
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            os.path.join(BASE_DIR, "templates"),
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "AI_Analyzer.context_processors.api_keys",  # 카카오 API 키 context processor 추가
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.contrib.gis.db.backends.spatialite",  # SpatiaLite 엔진으로 변경
        "NAME": BASE_DIR / "db.sqlite3",
        "OPTIONS": {
            "timeout": 60,  # 대용량 공간정보 DB를 위한 타임아웃 설정
            "init_command": "PRAGMA journal_mode=WAL;",  # 동시성 향상
        },
    }
}
AUTH_USER_MODEL = "custom_auth.User"

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "ko-kr"

TIME_ZONE = "Asia/Seoul"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

# Media files
MEDIA_URL = "media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Login settings
LOGIN_URL = "custom_auth:login"
LOGIN_REDIRECT_URL = "border:inquiry_list"
LOGOUT_REDIRECT_URL = "border:inquiry_list"

# RAG Settings
RAG_SETTINGS = RAG_SETTINGS
# Channels 설정
CHANNEL_LAYERS = {"default": {"BACKEND": "channels.layers.InMemoryChannelLayer"}}

# Leaflet 지도 설정 (AI_Analyzer에서 통합)
LEAFLET_CONFIG = {
    'DEFAULT_CENTER': (37.5665, 126.9780),  # 서울 중심 좌표
    'DEFAULT_ZOOM': 10,
    'MIN_ZOOM': 3,
    'MAX_ZOOM': 18,
    'DEFAULT_PRECISION': 6,
    'TILES': [
        ('OpenStreetMap', 'http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
            'attribution': '&copy; <a href="http://www.openstreetmap.org/copyright">OpenStreetMap</a>'
        }),
    ],
}

# 카카오 API 설정 (AI_Analyzer에서 통합)
KAKAO_REST_API_KEY = os.getenv('KAKAO_REST_API_KEY', '4b3a451741a307fa3db2b9273005146a')
KAKAO_JS_API_KEY = os.getenv('KAKAO_JS_API_KEY', '0ac2a982e676a58f9a4245749206f78b')

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "[{levelname}] {asctime} {name}:{lineno} - {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
    },
    "loggers": {
        # Django GIS GDAL 오류 로그 레벨 조정
        "django.contrib.gis": {
            "handlers": ["console"],
            "level": "WARNING",  # ERROR 대신 WARNING으로 설정하여 GDAL 오류 억제
            "propagate": False,
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "DEBUG",  # 개발 시엔 DEBUG, 운영 시엔 WARNING 이상 권장
    },
}
