# Generated by Django 5.2.1 on 2025-06-04 07:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0002_alter_conversationlog_user_id_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Prompt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "scope",
                    models.CharField(
                        choices=[("collection", "컬렉션"), ("user", "사용자")],
                        max_length=20,
                    ),
                ),
                ("content", models.TextField()),
                ("tag", models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name="conversationmessage",
            name="session",
        ),
        migrations.RemoveField(
            model_name="conversationsession",
            name="user",
        ),
        migrations.RemoveField(
            model_name="conversationsummary",
            name="session_id",
        ),
        migrations.RemoveField(
            model_name="conversationsummary",
            name="user_id",
        ),
        migrations.CreateModel(
            name="ChatSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_id",
                    models.CharField(editable=False, max_length=100, unique=True),
                ),
                ("title", models.SlugField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "lastload_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChatMemory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "memory_type",
                    models.CharField(
                        choices=[
                            ("question", "질문"),
                            ("answer", "답변"),
                            ("summary", "요약"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        blank=True,
                        choices=[("user", "User"), ("assistant", "Assistant")],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("content", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="chatbot.chatsession",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChatLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("log", models.JSONField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "session",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="log",
                        to="chatbot.chatsession",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CollectionMemory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("collection_name", models.CharField(max_length=100)),
                ("retrieved_documents_content", models.TextField()),
                ("retrieved_documents_meta", models.JSONField()),
                ("llm_response", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="chatbot.chatsession",
                    ),
                ),
                (
                    "prompt",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="chatbot.prompt",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="ConversationLog",
        ),
        migrations.DeleteModel(
            name="ConversationMessage",
        ),
        migrations.DeleteModel(
            name="ConversationSession",
        ),
        migrations.DeleteModel(
            name="ConversationSummary",
        ),
    ]
