# Generated by Django 5.2.1 on 2025-06-04 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0003_prompt_remove_conversationmessage_session_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatlog",
            name="log",
            field=models.JSONField(default=list),
        ),
    ]
