# Generated by Django 5.2.1 on 2025-06-04 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0004_alter_chatlog_log"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collectionmemory",
            name="retrieved_documents_content",
            field=models.JSONField(),
        ),
    ]
