# Generated by Django 5.2.1 on 2025-06-11 11:06

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LandValue",
            fields=[
                ("ogc_fid", models.AutoField(primary_key=True, serialize=False)),
                (
                    "a1",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="A1"
                    ),
                ),
                (
                    "a2",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="A2"
                    ),
                ),
                (
                    "a3",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="A3"
                    ),
                ),
                (
                    "a6",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="A6"
                    ),
                ),
                (
                    "a9",
                    models.FloatField(blank=True, null=True, verbose_name="공시지가"),
                ),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.GeometryField(
                        srid=5186, verbose_name="지오메트리"
                    ),
                ),
            ],
            options={
                "verbose_name": "공시지가",
                "verbose_name_plural": "공시지가",
                "db_table": "ltv_5186",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="LifePopGrid",
            fields=[
                ("ogc_fid", models.AutoField(primary_key=True, serialize=False)),
                (
                    "총생활인구수",
                    models.FloatField(
                        blank=True, null=True, verbose_name="총생활인구수"
                    ),
                ),
                (
                    "age_20",
                    models.FloatField(
                        blank=True, db_column="20대", null=True, verbose_name="20대"
                    ),
                ),
                (
                    "age_30",
                    models.FloatField(
                        blank=True, db_column="30대", null=True, verbose_name="30대"
                    ),
                ),
                (
                    "age_40",
                    models.FloatField(
                        blank=True, db_column="40대", null=True, verbose_name="40대"
                    ),
                ),
                (
                    "age_50",
                    models.FloatField(
                        blank=True, db_column="50대", null=True, verbose_name="50대"
                    ),
                ),
                (
                    "age_60",
                    models.FloatField(
                        blank=True, db_column="60대", null=True, verbose_name="60대"
                    ),
                ),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.PointField(
                        srid=5186, verbose_name="지오메트리"
                    ),
                ),
            ],
            options={
                "verbose_name": "생활인구 그리드",
                "verbose_name_plural": "생활인구 그리드",
                "db_table": "life_pop_grid_10m_5186",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="LongForeign",
            fields=[
                ("ogc_fid", models.AutoField(primary_key=True, serialize=False)),
                (
                    "총생활인구수",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="총생활인구수"
                    ),
                ),
                (
                    "중국인체류인구수",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="중국인체류인구수"
                    ),
                ),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.GeometryField(
                        srid=5186, verbose_name="지오메트리"
                    ),
                ),
            ],
            options={
                "verbose_name": "장기체류외국인",
                "verbose_name_plural": "장기체류외국인",
                "db_table": "long_foreign_25m_5186",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="PublicBuilding",
            fields=[
                ("ogc_fid", models.AutoField(primary_key=True, serialize=False)),
                (
                    "dgm_nm",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="건물명"
                    ),
                ),
                (
                    "lclas_cl",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="대분류"
                    ),
                ),
                (
                    "mlsfc_cl",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="중분류"
                    ),
                ),
                (
                    "dgm_ar",
                    models.FloatField(blank=True, null=True, verbose_name="면적"),
                ),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.GeometryField(
                        srid=5186, verbose_name="지오메트리"
                    ),
                ),
            ],
            options={
                "verbose_name": "공공건물",
                "verbose_name_plural": "공공건물",
                "db_table": "public_5186",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="School",
            fields=[
                ("ogc_fid", models.AutoField(primary_key=True, serialize=False)),
                (
                    "school_type",
                    models.CharField(
                        blank=True,
                        db_column="_학교종류",
                        max_length=255,
                        null=True,
                        verbose_name="학교종류",
                    ),
                ),
                (
                    "establishment_type",
                    models.CharField(
                        blank=True,
                        db_column="_설립구분_",
                        max_length=255,
                        null=True,
                        verbose_name="설립구분",
                    ),
                ),
                (
                    "standard_school",
                    models.CharField(
                        blank=True,
                        db_column="_표준학교",
                        max_length=255,
                        null=True,
                        verbose_name="표준학교",
                    ),
                ),
                (
                    "school_name",
                    models.CharField(
                        blank=True,
                        db_column="_학교명_",
                        max_length=255,
                        null=True,
                        verbose_name="학교명",
                    ),
                ),
                (
                    "english_name",
                    models.CharField(
                        blank=True,
                        db_column="_영문학교",
                        max_length=255,
                        null=True,
                        verbose_name="영문학교",
                    ),
                ),
                (
                    "authority",
                    models.CharField(
                        blank=True,
                        db_column="_관할조직",
                        max_length=255,
                        null=True,
                        verbose_name="관할조직",
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(
                        blank=True,
                        db_column="_도로명우",
                        max_length=255,
                        null=True,
                        verbose_name="도로명우편번호",
                    ),
                ),
                (
                    "road_address",
                    models.CharField(
                        blank=True,
                        db_column="_도로명주",
                        max_length=255,
                        null=True,
                        verbose_name="도로명주소",
                    ),
                ),
                (
                    "detail_address",
                    models.CharField(
                        blank=True,
                        db_column="_도로명상",
                        max_length=255,
                        null=True,
                        verbose_name="도로명상세주소",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        db_column="_전화번호_",
                        max_length=255,
                        null=True,
                        verbose_name="전화번호",
                    ),
                ),
                (
                    "homepage",
                    models.CharField(
                        blank=True,
                        db_column="_홈페이지",
                        max_length=255,
                        null=True,
                        verbose_name="홈페이지",
                    ),
                ),
                (
                    "fax_number",
                    models.CharField(
                        blank=True,
                        db_column="_팩스번호_",
                        max_length=255,
                        null=True,
                        verbose_name="팩스번호",
                    ),
                ),
                (
                    "x",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="X좌표"
                    ),
                ),
                (
                    "y",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Y좌표"
                    ),
                ),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, null=True, srid=5186, verbose_name="위치"
                    ),
                ),
            ],
            options={
                "verbose_name": "학교",
                "verbose_name_plural": "학교",
                "db_table": "school_5186",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="StorePoint",
            fields=[
                ("ogc_fid", models.AutoField(primary_key=True, serialize=False)),
                (
                    "uptaenm",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="업태명"
                    ),
                ),
                (
                    "service",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="서비스"
                    ),
                ),
                (
                    "area",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="면적"
                    ),
                ),
                (
                    "x",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="X좌표"
                    ),
                ),
                (
                    "y",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Y좌표"
                    ),
                ),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.PointField(
                        srid=5186, verbose_name="지오메트리"
                    ),
                ),
            ],
            options={
                "verbose_name": "상점",
                "verbose_name_plural": "상점",
                "db_table": "store_point_5186",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="TempForeign",
            fields=[
                ("ogc_fid", models.AutoField(primary_key=True, serialize=False)),
                (
                    "총생활인구수",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="총생활인구수"
                    ),
                ),
                (
                    "중국인체류인구수",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="중국인체류인구수"
                    ),
                ),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.GeometryField(
                        srid=5186, verbose_name="지오메트리"
                    ),
                ),
            ],
            options={
                "verbose_name": "단기체류외국인",
                "verbose_name_plural": "단기체류외국인",
                "db_table": "temp_foreign_25m_5186",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="WorkGrid",
            fields=[
                ("ogc_fid", models.AutoField(primary_key=True, serialize=False)),
                (
                    "총_직장_인구_수",
                    models.IntegerField(
                        blank=True,
                        db_column="총_직장_인구_수",
                        null=True,
                        verbose_name="총직장인구수",
                    ),
                ),
                (
                    "남성_직장_인구_수",
                    models.IntegerField(
                        blank=True,
                        db_column="남성_직장_인구_수",
                        null=True,
                        verbose_name="남성직장인구수",
                    ),
                ),
                (
                    "여성_직장_인구_수",
                    models.IntegerField(
                        blank=True,
                        db_column="여성_직장_인구_수",
                        null=True,
                        verbose_name="여성직장인구수",
                    ),
                ),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.GeometryField(
                        srid=5186, verbose_name="지오메트리"
                    ),
                ),
            ],
            options={
                "verbose_name": "직장인구 그리드",
                "verbose_name_plural": "직장인구 그리드",
                "db_table": "workgrid_10m_5186",
                "managed": False,
            },
        ),
    ]
