# Generated by Django 5.2.3 on 2025-06-13 08:29

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("GeoDB", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdministrativeDistrict",
            fields=[
                ("fid", models.AutoField(primary_key=True, serialize=False)),
                (
                    "emd_cd",
                    models.CharField(
                        help_text="8자리 행정동 코드",
                        max_length=8,
                        verbose_name="행정동코드",
                    ),
                ),
                (
                    "emd_eng_nm",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="영문행정동명",
                    ),
                ),
                (
                    "emd_kor_nm",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="한글행정동명",
                    ),
                ),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        srid=5186, verbose_name="행정구역경계"
                    ),
                ),
            ],
            options={
                "verbose_name": "행정동구역",
                "verbose_name_plural": "행정동구역",
                "db_table": "행정동구역",
                "ordering": ["emd_cd"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AdministrativeDistrictStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "emd_cd",
                    models.CharField(
                        max_length=8, unique=True, verbose_name="행정동코드"
                    ),
                ),
                (
                    "emd_kor_nm",
                    models.CharField(max_length=50, verbose_name="행정동명"),
                ),
                (
                    "total_population",
                    models.IntegerField(default=0, verbose_name="총 거주인구"),
                ),
                (
                    "total_working_population",
                    models.IntegerField(default=0, verbose_name="총 직장인구"),
                ),
                (
                    "total_foreign_visitors",
                    models.IntegerField(default=0, verbose_name="총 외국인 여행객"),
                ),
                (
                    "population_grid_count",
                    models.IntegerField(default=0, verbose_name="거주인구 그리드 수"),
                ),
                (
                    "working_grid_count",
                    models.IntegerField(default=0, verbose_name="직장인구 그리드 수"),
                ),
                (
                    "foreign_grid_count",
                    models.IntegerField(default=0, verbose_name="외국인 그리드 수"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="업데이트 시간"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성 시간"),
                ),
            ],
            options={
                "verbose_name": "행정동별 집계통계",
                "verbose_name_plural": "행정동별 집계통계",
                "db_table": "administrative_district_stats",
                "ordering": ["-total_population"],
                "managed": True,
            },
        ),
    ]
