# Generated by Django 5.2.3 on 2025-06-20 01:36

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("GeoDB", "0004_storeresult_emd_kor_nm"),
    ]

    operations = [
        migrations.CreateModel(
            name="SeoulDistrict",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "adm_sect_c",
                    models.CharField(
                        help_text="5자리 구별 코드 (11110: 종로구)",
                        max_length=10,
                        unique=True,
                        verbose_name="행정구역코드",
                    ),
                ),
                (
                    "sgg_nm",
                    models.CharField(
                        help_text="서울특별시 종로구",
                        max_length=100,
                        verbose_name="구명",
                    ),
                ),
                (
                    "sgg_oid",
                    models.FloatField(blank=True, null=True, verbose_name="구 OID"),
                ),
                (
                    "col_adm_se",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="행정구분"
                    ),
                ),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        srid=5186, verbose_name="구경계면"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성시간"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정시간"),
                ),
            ],
            options={
                "verbose_name": "서울시구별경계",
                "verbose_name_plural": "서울시구별경계",
                "db_table": "seoul_district",
                "ordering": ["adm_sect_c"],
                "managed": True,
            },
        ),
    ]
