# Generated by Django 5.2 on 2025-06-03 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("border", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="views",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
