# Generated by Django 5.2.3 on 2025-06-13 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("border", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="board_type",
            field=models.CharField(
                choices=[
                    ("inquiry", "문의 게시판"),
                    ("notice", "공지사항"),
                    ("portfolio", "포트폴리오"),
                ],
                max_length=10,
            ),
        ),
    ]
