# Generated by Django 5.2.1 on 2025-06-16 02:48

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("subject", models.CharField(max_length=255, verbose_name="제목")),
                (
                    "message",
                    models.TextField(
                        validators=[django.core.validators.MinLengthValidator(10)],
                        verbose_name="메시지",
                    ),
                ),
                ("recipient", models.EmailField(max_length=254, verbose_name="수신자")),
                ("sender", models.EmailField(max_length=254, verbose_name="발신자")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "대기중"),
                            ("sent", "전송됨"),
                            ("failed", "실패"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="전송일시"
                    ),
                ),
                (
                    "failed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="실패일시"
                    ),
                ),
                (
                    "failure_reason",
                    models.TextField(blank=True, verbose_name="실패 이유"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="email_messages",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "이메일 메시지",
                "verbose_name_plural": "이메일 메시지",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "created_at"],
                        name="smtp_emailm_status_21ed59_idx",
                    ),
                    models.Index(
                        fields=["recipient"], name="smtp_emailm_recipie_2ab99b_idx"
                    ),
                    models.Index(
                        fields=["user"], name="smtp_emailm_user_id_5e76ec_idx"
                    ),
                ],
            },
        ),
    ]
