# Generated by Django 5.2.1 on 2025-06-13 02:27

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EmailTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="템플릿 이름"
                    ),
                ),
                ("subject", models.CharField(max_length=255, verbose_name="제목")),
                ("body", models.TextField(verbose_name="본문")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="활성화 여부"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
            ],
            options={
                "verbose_name": "이메일 템플릿",
                "verbose_name_plural": "이메일 템플릿",
            },
        ),
        migrations.CreateModel(
            name="EmailMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("subject", models.CharField(max_length=255, verbose_name="제목")),
                (
                    "message",
                    models.TextField(
                        validators=[django.core.validators.MinLengthValidator(10)],
                        verbose_name="메시지",
                    ),
                ),
                ("recipient", models.EmailField(max_length=254, verbose_name="수신자")),
                ("sender", models.EmailField(max_length=254, verbose_name="발신자")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "대기중"),
                            ("sending", "전송중"),
                            ("sent", "전송완료"),
                            ("failed", "전송실패"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="전송일시"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, null=True, verbose_name="에러 메시지"),
                ),
                (
                    "retry_count",
                    models.PositiveIntegerField(default=0, verbose_name="재시도 횟수"),
                ),
                (
                    "max_retries",
                    models.PositiveIntegerField(
                        default=3, verbose_name="최대 재시도 횟수"
                    ),
                ),
                (
                    "is_encrypted",
                    models.BooleanField(default=False, verbose_name="암호화 여부"),
                ),
                (
                    "encryption_key",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="암호화 키"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="smtp.emailtemplate",
                        verbose_name="이메일 템플릿",
                    ),
                ),
            ],
            options={
                "verbose_name": "이메일 메시지",
                "verbose_name_plural": "이메일 메시지",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "created_at"],
                        name="smtp_emailm_status_21ed59_idx",
                    ),
                    models.Index(
                        fields=["recipient"], name="smtp_emailm_recipie_2ab99b_idx"
                    ),
                ],
            },
        ),
    ]
