# Generated by Django 5.2.1 on 2025-06-16 06:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("smtp", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="emailmessage",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "이메일",
                "verbose_name_plural": "이메일",
            },
        ),
        migrations.CreateModel(
            name="NewsletterSubscriber",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="이메일"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="수신 동의"),
                ),
                (
                    "subscribed_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="구독 시작일"),
                ),
                (
                    "unsubscribed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="구독 해지일"
                    ),
                ),
                (
                    "name",
                    models.CharField(blank=True, max_length=100, verbose_name="이름"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="newsletter_subscriptions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "뉴스레터 구독자",
                "verbose_name_plural": "뉴스레터 구독자",
                "indexes": [
                    models.Index(fields=["email"], name="smtp_newsle_email_46da71_idx"),
                    models.Index(
                        fields=["is_active"], name="smtp_newsle_is_acti_200cff_idx"
                    ),
                ],
            },
        ),
    ]
