# Generated by Django 5.2.3 on 2025-06-18 08:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AI_Analyzer", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalysisSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_id",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="세션 ID"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="세션 제목"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "lastload_at",
                    models.DateTimeField(auto_now=True, verbose_name="마지막 접근일시"),
                ),
                (
                    "analysis_result",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="AI_Analyzer.analysisresult",
                        verbose_name="분석 결과",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "분석 세션",
                "verbose_name_plural": "분석 세션",
                "ordering": ["-lastload_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AnalysisSessionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("log", models.JSONField(default=list, verbose_name="채팅 로그")),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
                (
                    "session",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="log",
                        to="AI_Analyzer.analysissession",
                        verbose_name="세션",
                    ),
                ),
            ],
            options={
                "verbose_name": "분석 세션 로그",
                "verbose_name_plural": "분석 세션 로그",
            },
        ),
    ]
