# Generated by Django 5.2.3 on 2025-06-24 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AI_Analyzer", "0002_analysissession_analysissessionlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysisresult",
            name="ai_explanation",
            field=models.TextField(blank=True, default="", verbose_name="AI 상세 설명"),
        ),
        migrations.AddField(
            model_name="analysisresult",
            name="ai_summary",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="AI 요약"
            ),
        ),
        migrations.AddField(
            model_name="analysisresult",
            name="is_member_analysis",
            field=models.BooleanField(default=False, verbose_name="회원 분석 여부"),
        ),
    ]
