# Generated by Django 5.2.3 on 2025-06-26 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AI_Analyzer", "0003_analysisresult_ai_explanation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysisresult",
            name="recommended_business_type_id",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="추천 업종 ID"
            ),
        ),
        migrations.AddField(
            model_name="analysisresult",
            name="recommended_business_type_name",
            field=models.CharField(
                blank=True, default="", max_length=50, verbose_name="추천 업종명"
            ),
        ),
        migrations.AddField(
            model_name="analysisresult",
            name="recommended_survival_percentage",
            field=models.FloatField(default=0, verbose_name="추천 업종 생존 확률 (%)"),
        ),
        migrations.AddField(
            model_name="analysisresult",
            name="recommended_survival_probability",
            field=models.FloatField(
                default=0, verbose_name="추천 업종 생존 확률 (0-1)"
            ),
        ),
    ]
