# Generated by Django 5.2.3 on 2025-06-26 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AI_Analyzer", "0004_analysisresult_recommended_business_type_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysisresult",
            name="business_recommendations",
            field=models.JSONField(
                blank=True, default=list, verbose_name="전체 업종 추천 결과"
            ),
        ),
    ]
